### ISSUE TITLE
ArduinoJson library used is V5. V6 syntax has changed for the buffer function

### ISSUE THREAD

**Issue by Judge-Tread** [MarkJB/wemos-d1-mini-esp8266-mqtt-sht30-temp-sensor#1]
`As the JsonBuffer, there are two versions of the JsonDocument.

The first is StaticJsonDocument, which is the equivalent of StaticJsonBuffer:

// ArduinoJson 5
StaticJsonBuffer<256> jb;

// ArduinoJson 6
StaticJsonDocument<256> doc;
The second is DynamicJsonDocument, which is the equivalent of DynamicJsonBuffer:

// ArduinoJson 5
DynamicJsonBuffer jb;

// ArduinoJson 6
DynamicJsonDocument doc(1024);
DynamicJsonDocument has a fixed capacity that you must specify to the constructor. Unlike the DynamicJsonBuffer, DynamicJsonDocument doesn’t automatically expand.`

https://arduinojson.org/v6/doc/upgrade/

**Comment by MarkJB** [comment]
Finally got around to updating the code for the ArduinoJson 6 library.
