### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Ludolacra** [MarkJB/wemos-d1-mini-esp8266-mqtt-sht30-temp-sensor#2]
https://github.com/MarkJB/wemos-d1-mini-esp8266-mqtt-sht30-temp-sensor/blob/e54a77c54404bd7317af7b7542e1daceb76f721f/mqtt_esp8266_sht30_temp_sensor.ino#L42

Please consider correcting the spelling mistake in the key, "humidity"

**Comment by MarkJB** [comment]
Thanks! Fixed in e528f54
